export const brandTokens = {
  colors: {
    primary: '#17171c',
    cohereBlack: '#000000',
    ink: '#212121',
    deepGreen: '#003c33',
    darkNavy: '#071829',
    canvas: '#ffffff',
    softStone: '#eeece7',
    paleGreen: '#edfce9',
    paleBlue: '#f1f5ff',
    hairline: '#d9d9dd',
    borderLight: '#e5e7eb',
    cardBorder: '#f2f2f2',
    muted: '#93939f',
    slate: '#75758a',
    bodyMuted: '#616161',
    actionBlue: '#1863dc',
    focusBlue: '#4c6ee6',
    coral: '#ff7759',
    coralSoft: '#ffad9b',
    formFocus: '#9b60aa',
    onPrimary: '#ffffff',
    onDark: '#ffffff',
    error: '#b30000',
  },
  typography: {
    fontFamilyBody: "'Unica77 Cohere Web', 'Inter', 'Arial', ui-sans-serif, system-ui, sans-serif",
    fontFamilyDisplay: "'CohereText', 'Space Grotesk', 'Inter', ui-sans-serif, system-ui, sans-serif",
    fontFamilyMono: "'CohereMono', 'Arial', ui-sans-serif, system-ui, sans-serif",
    heroDisplaySize: '96px',
    productDisplaySize: '72px',
    sectionDisplaySize: '60px',
    sectionHeadingSize: '48px',
    cardHeadingSize: '32px',
    featureHeadingSize: '24px',
    bodyLargeSize: '18px',
    bodySize: '16px',
    buttonSize: '14px',
    captionSize: '14px',
    microSize: '12px',
  },
  shape: {
    xs: 4,
    sm: 8,
    md: 16,
    lg: 22,
    xl: 30,
    pill: 32,
    full: 9999,
  },
  spacing: {
    xxs: 2,
    xs: 6,
    sm: 8,
    md: 12,
    lg: 16,
    xl: 24,
    xxl: 32,
    section: 80,
  },
} as const;
